### ISSUE TITLE
[3.0.207][32bit][HP Pavilion a6230n][NVIDIA GeForce 6150SE nForce 430] Unable to boot after successful installation on hdd

### ISSUE THREAD

**Issue by Blutgang** [JideTechnology/Remix-OS-For-PC#39]
(I know it's an old computer...)

1. Windows 7/10 - Install using the Remix OS installation tool
2. Reboot and choose Remix OS
3. Remix OS boots successfully after setup
4. Reboot and choose Remix OS
5. Remix OS attempts to boot 
6. After booting the kernel...there will be a black screen and the monitor will display - no video/display signal - which requires a hard shutdown

Adding `nomodeset` to the boot parameters will allow Remix OS to boot. (very slow - no hardware acceleration)

Log Files (Verbose Mode):

[cpuinfo_END-OF-INIT_HP-Pavilion_a6230n_3.0.207_x86_2016-12-10_20-49.txt](https://github.com/JideTechnology/Remix-OS-For-PC/files/644209/cpuinfo_END-OF-INIT_HP-Pavilion_a6230n_3.0.207_x86_2016-12-10_20-49.txt)

[dmesg_END-OF-INIT_HP-Pavilion_a6230n_3.0.207_x86_2016-12-10_20-49.txt](https://github.com/JideTechnology/Remix-OS-For-PC/files/644210/dmesg_END-OF-INIT_HP-Pavilion_a6230n_3.0.207_x86_2016-12-10_20-49.txt)

[dmidecode_END-OF-INIT_HP-Pavilion_a6230n_3.0.207_x86_2016-12-10_20-49.txt](https://github.com/JideTechnology/Remix-OS-For-PC/files/644212/dmidecode_END-OF-INIT_HP-Pavilion_a6230n_3.0.207_x86_2016-12-10_20-49.txt)

[lspci_END-OF-INIT_HP-Pavilion_a6230n_3.0.207_x86_2016-12-10_20-49.txt](https://github.com/JideTechnology/Remix-OS-For-PC/files/644213/lspci_END-OF-INIT_HP-Pavilion_a6230n_3.0.207_x86_2016-12-10_20-49.txt)

[lsusb_END-OF-INIT_HP-Pavilion_a6230n_3.0.207_x86_2016-12-10_20-49.txt](https://github.com/JideTechnology/Remix-OS-For-PC/files/644214/lsusb_END-OF-INIT_HP-Pavilion_a6230n_3.0.207_x86_2016-12-10_20-49.txt)

**Comment by Neurovert** [comment]
@Blutgang Have you tried booting with `EXTMOD=nouveau` grub parameter?
Follow this [**GUIDE**](http://support.jide.com/hc/en-us/articles/222778587--Hardware-Installation-Legacy-Boot-up-Troubleshooting) to apply the parameter for one-time test boot. Follow the guide's scheme, but apply the `EXTMOD=nouveau` parameter.

**Comment by Blutgang** [comment]
@Vioner Unfortunately, that parameter does not work. (no video/display signal)

**Comment by Neurovert** [comment]
It looks like there is no graphic driver for your card. I'm afraid we won't be able to add it. As far as I know it's not available. 
You can make sure of that by trying out any popular Linux distribution like Ubuntu/Fedora/Mint. If they don't support your card, there's no chance for support by Remix.

**Comment by Blutgang** [comment]
Oh well. Thank you for your assistance. Ubuntu seem to work with the proprietary NVIDIA legacy driver 304.xx (I doubt NVIDIA would provide driver support for ANDROID/Remix OS)
