### ISSUE TITLE
[3.0.207][32bit] Cannot install apps from play store using /data folder instead of data.img

### ISSUE THREAD

**Issue by xYuunaX** [JideTechnology/Remix-OS-For-PC#61]
Model: ASUS Transformer T100TA
OS: Remix OS 3.0.207 32bit

Problem:
I've been using data.img without any issues, apps install fine.
I re-installed and tried to use /data folder instead of data.img (to save space), but for some reason I cannot download any apps from the Play Store. (Giving me error code 963)

Troubleshooting Steps:
Booting up Linux and verified the /data folder, and I see files and folders. 
I've re-installed a few times , I tried the following comments/options in grub.cfg , tried DATA=/data and DATA=/RemixOS/data with no success.
Verified the permissions in Linux, everythings seems to be in order.

Thanks for your attention!

**Comment by Neurovert** [comment]
I'll check this within one week. Thanks for the report.

**Comment by xYuunaX** [comment]
Found fix for the issue: Format the HDD to ext4.

Sorry should of mentioned I was using NTFS partition previously.
