### ISSUE TITLE
Tip: Rotate screen button

### ISSUE THREAD

**Issue by jimgsey** [JideTechnology/Remix-OS-For-PC#63]
It would be good, for all those who have a tablet, to include in the settings or in the home bar a button to rotate the screen directly, since nothing appears in the settings.
It is very important for when the drivers recognize the screen but not the gyroscope and we are left rotated in another direction.
Many thanks and apologies for my English.

**Comment by Neurovert** [comment]
Thank you for the report. This feature has already been mentioned in issue [[3.0.206] Autorotation + toggle](https://github.com/JideTechnology/Remix-OS-For-PC/issues/10). Please upvote that issue or add comment to it. 
I'm closing this issue to avoid redundancy.
