### ISSUE TITLE
[3.0.207][64bit] Summoners war will not run 

### ISSUE THREAD

**Issue by tvcat** [JideTechnology/Remix-OS-For-PC#64]
I cant play the game (Summoners War) after recent game update.
it will detect the remis os as emulator and refused to run.
thanks.

**Comment by Neurovert** [comment]
Have you contacted the game developer about this? Most likely it's the game dev that has to enable Remix OS for playing the game.

**Comment by tvcat** [comment]
yes i had but they said that the game only allowed to play on mobile devices.
