### ISSUE TITLE
When new update?

### ISSUE THREAD

**Issue by jimgsey** [JideTechnology/Remix-OS-For-PC#77]
The last update is from november, now most change appears. 
I like this proyect, but now its stop?
Regards

**Comment by Neurovert** [comment]
@jide-bill 
Can you answer this one?

**Comment by marbledash1** [comment]
I to would like to know when the next update will be relaesed please is there going to be another beta release that we can try out as well?

**Comment by netship01** [comment]
And now phoenix has got nougat update.

**Comment by Neurovert** [comment]
@jide-opensource @jide-bill 
Can you please answer?

**Comment by jide-bill** [comment]
Currently, we still no concrete plan on when to release a new Android N
version for Android-x86.

**Comment by Witsonace** [comment]
Bill 4 Months now no update for Remix Os for PC 
And phoenix Os is one step ahead

**Comment by Witsonace** [comment]
@jide-bill no reply

**Comment by Neurovert** [comment]
@Witsonace I'm in direct contact with Bill. They still don't have any plans for PC...

**Comment by Witsonace** [comment]
Thanks for the info @vioner
