### ISSUE TITLE
Open source the OS

### ISSUE THREAD

**Issue by gabrc52** [JideTechnology/Remix-OS-For-PC#87]
Is the source code available?

If not, why? It would be better to open source this project, there would be more development and transparency.

**Comment by Neurovert** [comment]
True, I've asked for this multiple times, but Jide's decision to keep OS features closed source remains persistent.

The kernel and installer is open, you can find all the code Jide shares here [JideTechnology profile](https://github.com/JideTechnology)

**Comment by Neurovert** [comment]
@jide-bill Maybe you also can answer the question.

**Comment by jide-opensource** [comment]
sorry. we have no plan to open source Remix OS.

**Comment by marzzzello** [comment]
Since development is now discontinued it would be nice to release the source code so the communtiy can work on it

**Comment by Neurovert** [comment]
@jide-bill @jide-opensource 
As I understood from your announcement, Remix OS will be used in cooperation with your enterprise partners right? So it means that you will not open source Remix OS for PC? 

Please update us on the topic.

**Comment by Neurovert** [comment]
Remix OS for PC will remain closed source:
https://i.imgur.com/QECDaOC.png
